--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY pck_px IS
PORT(
  pad	: IN STD_LOGIC;
  ck	: OUT STD_LOGIC;
  vdde	: IN STD_LOGIC;
  vddi	: IN STD_LOGIC;
  vsse	: IN STD_LOGIC;
  vssi	: IN STD_LOGIC
);
END pck_px;

ARCHITECTURE RTL OF pck_px IS
BEGIN
  ck <= pad;
END RTL;
