--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY pi_px IS
PORT(
  pad	: IN STD_LOGIC;
  t	: OUT STD_LOGIC;
  ck	: IN STD_LOGIC;
  vdde	: IN STD_LOGIC;
  vddi	: IN STD_LOGIC;
  vsse	: IN STD_LOGIC;
  vssi	: IN STD_LOGIC
);
END pi_px;

ARCHITECTURE RTL OF pi_px IS
BEGIN
  t <= pad;
END RTL;
