--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY po_px IS
PORT(
  i	: IN STD_LOGIC;
  pad	: OUT STD_LOGIC;
  ck	: IN STD_LOGIC;
  vdde	: IN STD_LOGIC;
  vddi	: IN STD_LOGIC;
  vsse	: IN STD_LOGIC;
  vssi	: IN STD_LOGIC
);
END po_px;

ARCHITECTURE RTL OF po_px IS
BEGIN
  pad <= i;
END RTL;
