--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY pvssi_px IS
PORT(
  ck	: IN STD_LOGIC;
  vdde	: IN STD_LOGIC;
  vddi	: IN STD_LOGIC;
  vsse	: IN STD_LOGIC;
  vssi	: IN STD_LOGIC
);
END pvssi_px;

ARCHITECTURE RTL OF pvssi_px IS
BEGIN
END RTL;
