--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY rowend_x0 IS
PORT(
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
);
END rowend_x0;

ARCHITECTURE RTL OF rowend_x0 IS
BEGIN
END RTL;
