--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY tie_x0 IS
PORT(
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
);
END tie_x0;

ARCHITECTURE RTL OF tie_x0 IS
BEGIN
END RTL;
